services:
  postgres:
    image: postgres:16
    container_name: sahty_postgres
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: sahty
      POSTGRES_PASSWORD: sahty_dev_2026
      POSTGRES_DB: sahty_emr
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U sahty -d sahty_emr"]
      interval: 10s
      timeout: 5s
      retries: 5

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: sahty_pgadmin
    restart: unless-stopped
    ports:
      - "5050:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@sahty.dev
      PGADMIN_DEFAULT_PASSWORD: admin123
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    depends_on:
      postgres:
        condition: service_healthy

  whoicd:
    image: whoicd/icd-api:latest
    container_name: sahty_icd_api
    restart: unless-stopped
    ports:
      - "8090:80"
    environment:
      acceptLicense: "true"
      saveAnalytics: "false"
      include: "2024-01_en-fr"

  minio:
    image: minio/minio
    container_name: sahty_minio
    restart: always
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: admin
      MINIO_ROOT_PASSWORD: admin123
    command: server /data --console-address ":9001"
    volumes:
      - minio_data:/data

volumes:
  pgdata:
  pgadmin_data:
  minio_data:
