import React, { useState, useEffect } from 'react';
import { 
  Plus, 
  Archive, 
  Trash2, 
  Pencil, 
  Save, 
  X, 
  ChevronRight, 
  AlertCircle,
  Activity,
  Scissors,
  Users,
  Calendar,
  Droplet,
  Bot
} from 'lucide-react';

// --- Types ---

type AntecedentCategory = 'Médicaux' | 'Chirurgicaux' | 'Familiaux' | 'Gynéco-obstétriques' | 'Autres';

interface Antecedent {
  id: string;
  category: AntecedentCategory;
  description: string;
  date?: string; // Année ou date précise
  notes?: string;
  isChronic: boolean;
  isAutoGenerated?: boolean;
}

const MOCK_ANTECEDANTS: Antecedent[] = [
  {
    id: '1',
    category: 'Médicaux',
    description: 'Hypertension Artérielle',
    date: '2015',
    notes: 'Sous traitement (Amlodipine)',
    isChronic: true
  },
  {
    id: '2',
    category: 'Chirurgicaux',
    description: 'Appendicectomie',
    date: '2008',
    isChronic: false
  },
  {
    id: '3',
    category: 'Familiaux',
    description: 'Diabète Type 2 (Père)',
    isChronic: false
  }
];

const INITIAL_FORM: Partial<Antecedent> = {
  category: 'Médicaux',
  description: '',
  date: '',
  notes: '',
  isChronic: false
};

export const Antecedants: React.FC = () => {
  const [items, setItems] = useState<Antecedent[]>(MOCK_ANTECEDANTS);
  const [isModalOpen, setIsModalOpen] = useState(false);
  const [formData, setFormData] = useState<Partial<Antecedent>>(INITIAL_FORM);

  // Écouteur d'événement pour l'ajout automatique depuis le module Transfusion
  useEffect(() => {
    const handleAutoTransfusion = (event: any) => {
      const record = event.detail;
      const dateYear = record.date.split('-')[0];
      
      const newAntecedent: Antecedent = {
        id: `auto-trans-${Date.now()}`,
        category: 'Médicaux',
        description: `Transfusion : ${record.productType}`,
        date: dateYear,
        isChronic: record.tolerance === 'Incident', // On marque comme "chronique/critique" si incident
        isAutoGenerated: true,
        notes: `[GÉNÉRÉ AUTOMATIQUEMENT] Déduit de la transfusion renseignée le ${new Date(record.date).toLocaleDateString()}. Poche n°${record.pouchNumber}. ${record.tolerance === 'Incident' ? `ALERTE INCIDENT : ${record.incidentType} - ${record.incidentDescription}` : 'Tolérance : Bonne.'}`
      };

      setItems(prev => [newAntecedent, ...prev]);
    };

    window.addEventListener('patient-transfused', handleAutoTransfusion);
    return () => window.removeEventListener('patient-transfused', handleAutoTransfusion);
  }, []);

  const handleInputChange = (e: React.ChangeEvent<HTMLInputElement | HTMLSelectElement | HTMLTextAreaElement>) => {
    const { name, value, type } = e.target;
    if (type === 'checkbox') {
      const checked = (e.target as HTMLInputElement).checked;
      setFormData(prev => ({ ...prev, [name]: checked }));
    } else {
      setFormData(prev => ({ ...prev, [name]: value }));
    }
  };

  const handleSave = () => {
    if (!formData.description) return;

    if (formData.id) {
      setItems(prev => prev.map(item => item.id === formData.id ? { ...formData as Antecedent } : item));
    } else {
      const newItem = { ...formData, id: Date.now().toString() } as Antecedent;
      setItems([newItem, ...items]);
    }

    setIsModalOpen(false);
    setFormData(INITIAL_FORM);
  };

  const handleEdit = (item: Antecedent) => {
    setFormData(item);
    setIsModalOpen(true);
  };

  const handleDelete = (id: string) => {
    if (window.confirm('Voulez-vous vraiment supprimer cet antécédent ?')) {
      setItems(prev => prev.filter(item => item.id !== id));
    }
  };

  const getCategoryStyles = (category: AntecedentCategory, isAuto: boolean = false) => {
    if (isAuto) return { bg: 'bg-emerald-50', text: 'text-emerald-700', border: 'border-emerald-200', icon: Bot };
    
    switch (category) {
      case 'Médicaux': return { bg: 'bg-blue-50', text: 'text-blue-700', border: 'border-blue-200', icon: Activity };
      case 'Chirurgicaux': return { bg: 'bg-rose-50', text: 'text-rose-700', border: 'border-rose-200', icon: Scissors };
      case 'Familiaux': return { bg: 'bg-emerald-50', text: 'text-emerald-700', border: 'border-emerald-200', icon: Users };
      case 'Gynéco-obstétriques': return { bg: 'bg-purple-50', text: 'text-purple-700', border: 'border-purple-200', icon: Users };
      default: return { bg: 'bg-gray-50', text: 'text-gray-700', border: 'border-gray-200', icon: Archive };
    }
  };

  return (
    <div className="space-y-6">
      <div className="flex justify-between items-center">
        <div>
          <h3 className="text-lg font-semibold text-gray-800 flex items-center">
            <Archive className="mr-2 text-indigo-600" />
            Antécédants du Patient
          </h3>
          <p className="text-sm text-gray-500">Historique médical, chirurgical et familial complet.</p>
        </div>
        <button 
          onClick={() => { setFormData(INITIAL_FORM); setIsModalOpen(true); }}
          className="flex items-center space-x-2 bg-indigo-600 hover:bg-indigo-700 text-white px-4 py-2 rounded-lg transition-colors shadow-sm font-medium"
        >
          <Plus size={18} />
          <span>Ajouter un antécédent</span>
        </button>
      </div>

      {items.length === 0 ? (
        <div className="text-center py-16 bg-white rounded-xl border border-dashed border-gray-300">
          <Archive className="mx-auto h-12 w-12 text-gray-300 mb-3" />
          <p className="text-gray-500 font-medium">Aucun antécédent enregistré pour ce patient.</p>
        </div>
      ) : (
        <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-4">
          {items.map(item => {
            const styles = getCategoryStyles(item.category, item.isAutoGenerated);
            const Icon = styles.icon;
            return (
              <div key={item.id} className={`bg-white rounded-xl border-2 ${item.isAutoGenerated ? 'border-emerald-100 shadow-emerald-50' : 'border-gray-100'} p-5 shadow-sm hover:shadow-md transition-all group relative overflow-hidden`}>
                <div className="flex justify-between items-start mb-3">
                  <span className={`inline-flex items-center px-2.5 py-0.5 rounded-full text-[10px] font-bold uppercase border ${styles.bg} ${styles.text} ${styles.border}`}>
                    <Icon size={12} className="mr-1" />
                    {item.isAutoGenerated ? 'Système' : item.category}
                  </span>
                  <div className="flex space-x-1">
                    {!item.isAutoGenerated && <button onClick={() => handleEdit(item)} className="p-1.5 text-gray-400 hover:text-indigo-600 hover:bg-indigo-50 rounded transition-colors" title="Modifier"><Pencil size={14} /></button>}
                    <button onClick={() => handleDelete(item.id)} className="p-1.5 text-gray-400 hover:text-red-600 hover:bg-red-50 rounded transition-colors" title="Supprimer"><Trash2 size={14} /></button>
                  </div>
                </div>

                <h4 className="text-lg font-bold text-gray-900 mb-1 flex items-center">
                  {item.description}
                  {item.isChronic && (
                    <span className="ml-2 px-1.5 py-0.5 bg-rose-100 text-rose-700 text-[10px] font-bold rounded" title="Alerte ou Maladie chronique">Alerte</span>
                  )}
                </h4>
                
                {item.date && (
                  <div className="text-sm text-gray-500 flex items-center mb-2">
                    <Calendar size={14} className="mr-1" />
                    {item.date}
                  </div>
                )}

                {item.notes && (
                  <p className={`text-xs p-2 rounded-lg border mt-2 italic ${item.isAutoGenerated ? 'bg-emerald-50/50 border-emerald-100 text-emerald-800 font-medium' : 'bg-gray-50 border-gray-100 text-gray-600'}`}>
                    {item.notes}
                  </p>
                )}
                
                {item.isAutoGenerated && (
                  <div className="absolute bottom-1 right-2 opacity-5 text-emerald-900">
                    <Bot size={40} />
                  </div>
                )}
              </div>
            );
          })}
        </div>
      )}

      {/* --- Modal Form --- */}
      {isModalOpen && (
        <div className="fixed inset-0 z-50 flex items-center justify-center p-4 bg-black/60 backdrop-blur-sm">
          <div className="bg-white rounded-xl shadow-2xl w-full max-w-lg overflow-hidden animate-in fade-in zoom-in-95 duration-200">
            <div className="px-6 py-4 border-b border-gray-200 flex justify-between items-center bg-gray-50">
              <h3 className="text-lg font-bold text-gray-900 flex items-center">
                <Archive size={20} className="mr-2 text-indigo-600"/>
                {formData.id ? 'Modifier l\'antécédent' : 'Nouvel antécédent'}
              </h3>
              <button onClick={() => setIsModalOpen(false)} className="text-gray-400 hover:text-gray-600"><X size={20}/></button>
            </div>
            
            <div className="p-6 space-y-5">
              <div>
                <label className="block text-sm font-bold text-gray-700 mb-1">Catégorie *</label>
                <select 
                  name="category" 
                  value={formData.category} 
                  onChange={handleInputChange} 
                  className="w-full border-gray-300 rounded-lg shadow-sm focus:ring-indigo-500 focus:border-indigo-500 px-4 py-3 text-sm"
                >
                  <option value="Médicaux">Médicaux</option>
                  <option value="Chirurgicaux">Chirurgicaux</option>
                  <option value="Familiaux">Familiaux</option>
                  <option value="Gynéco-obstétriques">Gynéco-obstétriques</option>
                  <option value="Autres">Autres</option>
                </select>
              </div>

              <div>
                <label className="block text-sm font-bold text-gray-700 mb-1">Description *</label>
                <input 
                  type="text" 
                  name="description" 
                  value={formData.description} 
                  onChange={handleInputChange} 
                  placeholder="Ex: Diabète type 2, Appendicectomie..."
                  className="w-full border-gray-300 rounded-lg shadow-sm focus:ring-indigo-500 focus:border-indigo-500 px-4 py-3 text-sm"
                  autoFocus
                />
              </div>

              <div className="grid grid-cols-2 gap-4">
                <div>
                  <label className="block text-sm font-bold text-gray-700 mb-1">Date / Année</label>
                  <input 
                    type="text" 
                    name="date" 
                    value={formData.date} 
                    onChange={handleInputChange} 
                    placeholder="Ex: 2018 ou 12/2020"
                    className="w-full border-gray-300 rounded-lg shadow-sm focus:ring-indigo-500 focus:border-indigo-500 px-4 py-3 text-sm"
                  />
                </div>
                <div className="flex items-center pt-6">
                  <label className="inline-flex items-center cursor-pointer">
                    <input 
                      type="checkbox" 
                      name="isChronic" 
                      checked={formData.isChronic} 
                      onChange={handleInputChange}
                      className="h-5 w-5 text-rose-600 focus:ring-rose-500 border-gray-300 rounded" 
                    />
                    <span className="ml-2 text-sm font-bold text-gray-700">Maladie chronique</span>
                  </label>
                </div>
              </div>

              <div>
                <label className="block text-sm font-bold text-gray-700 mb-1">Notes complémentaires</label>
                <textarea 
                  name="notes" 
                  value={formData.notes} 
                  onChange={handleInputChange} 
                  rows={3} 
                  placeholder="Traitements actuels, complications, détails..."
                  className="w-full border-gray-300 rounded-lg shadow-sm focus:ring-indigo-500 focus:border-indigo-500 px-4 py-3 text-sm"
                />
              </div>
            </div>

            <div className="px-6 py-4 border-t border-gray-200 bg-gray-50 flex justify-end space-x-3">
              <button onClick={() => setIsModalOpen(false)} className="px-5 py-2.5 text-gray-700 hover:bg-gray-200 rounded-lg text-sm font-bold transition-colors">Annuler</button>
              <button 
                onClick={handleSave} 
                disabled={!formData.description} 
                className="px-5 py-2.5 bg-indigo-600 text-white hover:bg-indigo-700 rounded-lg text-sm font-bold shadow-lg transition-colors flex items-center disabled:opacity-50"
              >
                <Save size={18} className="mr-2"/> Enregistrer
              </button>
            </div>
          </div>
        </div>
      )}
    </div>
  );
};